name: Build and push Docker image

on:
  workflow_dispatch:
  
env:
  r_version: 4.5.0

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test that dependencies were successfully installed
        uses: docker/build-push-action@v5
        with:
          target: cimage-deps-test
          load: true
          build-args: |
            NUM_BUILD_CORES=4
            R_VERSION=${{ env.r_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test that dependencies still work in the runtime stage
        uses: docker/build-push-action@v5
        with:
          target: cimage-runtime-test
          load: true
          build-args: |
            NUM_BUILD_CORES=4
            R_VERSION=${{ env.r_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          target: cimage-deps
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-cimage-base:R${{ env.r_version }}
            ghcr.io/${{ github.repository_owner }}/docker-cimage-base:latest
          build-args: |
            NUM_BUILD_CORES=4
            R_VERSION=${{ env.r_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push runtime image
        uses: docker/build-push-action@v5
        with:
          target: cimage-runtime
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-cimage-runtime:R${{ env.r_version }}
            ghcr.io/${{ github.repository_owner }}/docker-cimage-runtime:latest
          build-args: |
            NUM_BUILD_CORES=4
            R_VERSION=${{ env.r_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push R base
        uses: docker/build-push-action@v5
        with:
          target: r-base
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-cimage-r-base:R${{ env.r_version }}
            ghcr.io/${{ github.repository_owner }}/docker-cimage-r-base:latest
          build-args: |
            NUM_BUILD_CORES=4
            R_VERSION=${{ env.r_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
